github:
  description: "Website sources for the Apache OzHera(Incubating) website"
  homepage: https://ozhera.apache.org/
  labels:
    - apache
    - Apache OzHera(Incubating)
    - website

staging:
  profile: ~
  whoami: preview

publish:
  whoami: asf-site
