github:
  description: "Website sources for the Apache OzHera(Incubating) website"
  homepage: https://ozhera.apache.org/
  labels:
    - apache
    - Apache OzHera(Incubating)
    - website

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
staging:
  profile:
  whoami: preview

publish:
  whoami: asf-site
